### Loading into Pandas

In [1]:
import pandas as pd

In [12]:
#df=pd.read_csv("pokemon_data.csv")
#df.head(5)
df=pd.read_csv("pokemon_data.txt",delimiter="\t")
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

### Reading data in pandas

In [32]:
# Reading Header
print(df.columns)
# Reading Column
print(df[["Name","HP","Attack"]])
# Reading Row
print(df.iloc[1])
# Reading specific location (R,C)
print(df.iloc[2,1])  # To find whats in that specific location

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
                      Name  HP  Attack
0                Bulbasaur  45      49
1                  Ivysaur  60      62
2                 Venusaur  80      82
3    VenusaurMega Venusaur  80     100
4               Charmander  39      52
..                     ...  ..     ...
795                Diancie  50     100
796    DiancieMega Diancie  50     160
797    HoopaHoopa Confined  80     110
798     HoopaHoopa Unbound  80     160
799              Volcanion  80     110

[800 rows x 3 columns]
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object
Venusaur

In [36]:
# For printing the fire type pokemons:-
df.loc[df["Type 1"]=="Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Sorting/Describing data

In [37]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [39]:
df.sort_values("Name",ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [41]:
df.sort_values(["Type 1","HP"])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

### Making changes to Data

In [42]:
df["Total"]=df["HP"]+df["Attack"]+df["Defense"]+df["Speed"]+df["Sp. Atk"]+df["Sp. Def"]

In [44]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [49]:
df=df.drop(columns=["Total"])  # dropping the column "Total"

In [50]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [51]:
df["Total"]=df.iloc[:,4:10].sum(axis=1)

In [52]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

### Saving our data (Exporting into desired format)

In [53]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [55]:
df.to_csv("Modified.csv",index=False)

### Filtering the Data

In [65]:
legend_grass=df.loc[(df["Type 1"]=="Grass")&(df["Type 2"]=="Poison")&(df["HP"]>70)] # for finding grass-poison types with HP greater than 70
legend_grass

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464

In [73]:
legend_fire=df.loc[(df["Type 1"]=="Fire")&(df["HP"]>70)]
legend_fire

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False,505
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,555
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,580
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False,534
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False,530
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False,534
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False,540
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True,600
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False,528
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False,498
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False,480
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False,540
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False,484
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False,534
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False,499
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [74]:
legend_grass.to_csv("Filtered grass pokemons.csv")

In [76]:
legend_fire=legend_fire.reset_index()

In [79]:
df.loc[df["Name"].str.contains("Mega")] #with mega

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False,630
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False,495
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False,590
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False,590
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False,600
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False,590
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False,640
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False,615
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True,780
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False,525
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False,610
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False,610
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False,600
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,600
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False,700
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False,630
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False,635
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False,618
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False,480
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False,480
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False,630
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False,510
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False,575
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False,560
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False,590
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False,555
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False,565
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False,580
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False,700
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False,700
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True,700
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True,700
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True,780
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False,580
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False,700
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False,618
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False,545
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700

In [81]:
import re
df.loc[df["Type 1"].str.contains("Fire|Grass",regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [84]:
df.loc[df["Name"].str.contains("^Pi[a-z]*",regex=True)] # pokemons starting with "Pi"

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,314
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

### Conditional Changes

In [96]:
df.loc[df["Type 1"]=="Flamer","Type 1"]="Fire"
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

### Aggregate statistics using the GroupBy

In [97]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [100]:
df.groupby(["Type 1"]).mean().sort_values("Defense",ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148,487.703704
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909,453.750000
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000,550.531250
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000,437.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500,439.562500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714,430.455357
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333,433.458333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857,421.142857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000,378.927536
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516,445.741935
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000,399.142857
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154,458.076923
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614,475.947368
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909,443.409091
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000,485.000000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000,416.444444
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824,413.176471
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408,401.683673

In [101]:
df.groupby(["Type 1"]).count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112

In [102]:
df["count"]=1

In [104]:
df.groupby(["Type 1","Type 2"]).count()["count"]

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64